version: "3.7"

services: 
    app:
        restart: always
        build: .
        ports: 
            - 5000:5000
        volumes:
            - '.:/web'
        depends_on:
            - db
    db:
        restart: always
        image: postgres:12.2
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}



